#Configuration file used in DEVELOPEMENT. 
## NOTE: if you get this error: 
# Near line 0 (last key parsed ''): bare keys cannot contain '\ufeff'
# It is because this config.toml file is saved with BOM. Notepad does it, please use "save as.." with UTF-8 without BOM.

#used to develop under windows


ServiceURL = "127.0.0.1:5549" # 5549 is a develop test 5548 is the deployed
RootURLPattern = "/omx/"
UseRelativeRoot = true
DebugVerbose = false
#OmxCmdParams = "-o,hdmi" #comma separated, example -o,local. Could not be empty 
DBPath= "../db/test-data-windows.db"
TmpInfo= "../tmp"
VueLibName = "vue.js"
VideoDir="c:\\local\\Video"
MusicDir="c:\\local\\Music"

[Player]
Path="C:\\Program Files\\VideoLAN\\VLC\\vlc.exe"
Params="-I dummy --dummy-quiet"

[SoundCloud]
IsAvailable = true
CfgFile = "plugin/soundcloud.json"
ClientID=""
AuthToken=""
UserAgent=""
