// Code generated by "stringer -type=actionTD"; DO NOT EDIT.

package omx

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[actTerminate-0]
	_ = x[actPlaying-1]
	_ = x[actPause-2]
}

const _actionTD_name = "actTerminateactPlayingactPause"

var _actionTD_index = [...]uint8{0, 12, 22, 30}

func (i actionTD) String() string {
	if i < 0 || i >= actionTD(len(_actionTD_index)-1) {
		return "actionTD(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _actionTD_name[_actionTD_index[i]:_actionTD_index[i+1]]
}
